import { createRouter, createWebHistory } from 'vue-router'
import { useUserStore } from '../stores/user'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/login', component: () => import('../views/login/index.vue') },
    {
      path: '/ims',
      component: () => import('../layouts/BasicLayout.vue'),
      children: [
        { path: 'home', component: () => import('../views/home/index.vue') },
        { path: 'workbench', component: () => import('../views/workbench/index.vue') },
        { path: 'workbench/todos', component: () => import('../views/workbench/todos.vue') },
        { path: 'workbench/messages', component: () => import('../views/workbench/messages.vue') },
        { path: 'ip-group', component: () => import('../views/ip-group/index.vue') },
        { path: 'live/sessions', component: () => import('../views/live/index.vue') },
        { path: 'live/alarm', component: () => import('../views/live/alarm.vue') },
        { path: 'cost', component: () => import('../views/cost/index.vue') },
        { path: 'fin/cost', component: () => import('../views/fin/cost.vue') },
        { path: 'fin/profit', component: () => import('../views/fin/profit.vue') },
        { path: 'fin/dashboard', component: () => import('../views/fin/dashboard.vue') },
        { path: 'fin/profit-trace', component: () => import('../views/fin/profit-trace.vue') },
        { path: 'fin/share/rule', component: () => import('../views/fin/share-rule.vue') },
        { path: 'fin/share/result', component: () => import('../views/fin/share-result.vue') },
        { path: 'fin/ledger', component: () => import('../views/fin/ledger.vue') },
        { path: 'content/sop', component: () => import('../views/content/sop.vue') },
        { path: 'content/topic', component: () => import('../views/content/topic.vue') },
        { path: 'content/plan', component: () => import('../views/content/plan.vue') },
        { path: 'content/review', component: () => import('../views/content/review.vue') },
        { path: 'content/work-task', component: () => import('../views/content/work-task.vue') },
        { path: 'content/task', component: () => import('../views/content/task.vue') },
        { path: 'content/task/:id/execute', component: () => import('../views/content/task-execute.vue') },
        { path: 'content/task/execute', redirect: '/ims/content/task' },
        { path: 'master', component: () => import('../views/master/index.vue') },
        { path: 'content/list', component: () => import('../views/content/list.vue') },
        { path: 'content/fb-sync', component: () => import('../views/content/fb-sync.vue') },
        { path: 'content/publish', component: () => import('../views/content/publish.vue') },
        { path: 'collect/task', component: () => import('../views/collect/task.vue') },
        { path: 'collect/log', component: () => import('../views/collect/log.vue') },
        { path: 'collect/kuaishou', component: () => import('../views/collect/kuaishou.vue') },
        { path: 'collect/douyin', component: () => import('../views/collect/douyin.vue') },
        { path: 'collect/wechat-channels', component: () => import('../views/collect/wechat-channels.vue') },
        { path: 'collect/external/account', component: () => import('../views/collect/external-account.vue') },
        { path: 'collect/external/keyword', component: () => import('../views/collect/external-keyword.vue') },
        { path: 'collect/metadata', component: () => import('../views/collect/metadata.vue') },
        { path: 'collect/threshold', component: () => import('../views/collect/threshold.vue') },
        { path: 'bi/query/perf', component: () => import('../views/bi/query-perf.vue') },
        { path: 'bi/query', component: () => import('../views/bi/query.vue') },
        { path: 'bi/report/list', component: () => import('../views/bi/report-list.vue') },
        { path: 'bi/report/designer', component: () => import('../views/bi/designer.vue') },
        { path: 'bi/report', component: () => import('../views/bi/report.vue') },
        { path: 'bi/metric', component: () => import('../views/bi/metric.vue') },
        { path: 'bi/analysis', component: () => import('../views/bi/analysis.vue') },
        { path: 'bi/report/subscribe', component: () => import('../views/bi/subscribe.vue') },
        { path: 'bi/report/preview', component: () => import('../views/bi/preview.vue') },
        { path: 'bi/screen-config', component: () => import('../views/bi/screen-config.vue') },
        { path: 'bi/screen/:id/view', component: () => import('../views/bi/screen-view.vue') },
        { path: 'flow', component: () => import('../views/flow/index.vue') },
        { path: 'analysis/query-tool', component: () => import('../views/analysis/query-tool.vue') },
        { path: 'eff', component: () => import('../views/eff/index.vue') },
        { path: 'int/work', component: () => import('../views/int/work.vue') },
        { path: 'int/account', component: () => import('../views/int/account.vue') },
        { path: 'comp/work', component: () => import('../views/comp/work.vue') },
        { path: 'comp/account', component: () => import('../views/comp/account.vue') },
        { path: 'comp/library', component: () => import('../views/comp/library.vue') },
        { path: 'monitor/theme', component: () => import('../views/monitor/theme.vue') },
        { path: 'meet/daily', component: () => import('../views/meet/daily.vue') },
        { path: 'meet/daily/submit', component: () => import('../views/meet/daily-submit.vue') },
        { path: 'meet/daily/team', component: () => import('../views/meet/daily-team.vue') },
        { path: 'meet/daily/review', component: () => import('../views/meet/daily-review.vue') },
        { path: 'meet/daily/stat', component: () => import('../views/meet/daily-stat.vue') },
        { path: 'meet/minutes', component: () => import('../views/meet/minutes.vue') },
        { path: 'report/template', component: () => import('../views/report/template.vue') },
        { path: 'report/submission', component: () => import('../views/report/submission.vue') },
        { path: 'report/stat', component: () => import('../views/report/stat.vue') },
        { path: 'train/material', component: () => import('../views/train/material.vue') },
        { path: 'train/task', component: () => import('../views/train/task.vue') },
        { path: 'train/study/:taskId', component: () => import('../views/train/study.vue') },
        { path: 'air/kb', component: () => import('../views/air/kb.vue') },
        { path: 'air/skill', component: () => import('../views/air/skill.vue') },
        { path: 'air/expert', component: () => import('../views/air/expert.vue') },
        { path: 'air/cfg', component: () => import('../views/air/cfg.vue') },
        { path: 'perf/metric', component: () => import('../views/perf/metric.vue') },
        { path: 'perf/calc', component: () => import('../views/perf/calc.vue') },
        { path: 'perf/mine', component: () => import('../views/perf/mine.vue') },
        { path: 'perf/scheme', component: () => import('../views/perf/scheme.vue') },
        { path: 'perf/execution', component: () => import('../views/perf/execution.vue') },
        { path: 'perf/result', component: () => import('../views/perf/result.vue') },
        { path: 'perf/exam', component: () => import('../views/perf/exam.vue') },
        { path: 'meet', component: () => import('../views/meet/index.vue') },
        { path: 'train/stat', component: () => import('../views/train/stat.vue') },
        { path: 'content/layout', component: () => import('../views/content/layout.vue') },
        { path: 'content/layout-template', redirect: '/ims/content/layout' },
        { path: 'dc/dashboard', component: () => import('../views/dc/dashboard.vue') },
        { path: 'dc/trace/perf', component: () => import('../views/dc/perf.vue') },
        { path: 'dc/trace', component: () => import('../views/dc/trace.vue') },
        { path: 'dc/dashboard', component: () => import('../views/dc/dashboard.vue') },
        { path: 'alert/rule', component: () => import('../views/alert/rule.vue') },
        { path: 'alert/live', component: () => import('../views/alert/live.vue') },
        { path: 'alert/stats', component: () => import('../views/alert/stats.vue') },
        { path: 'alert/escalate', component: () => import('../views/alert/escalate.vue') },
        { path: 'cost/account', redirect: '/ims/cost' },
        { path: 'cost/roi', redirect: '/ims/cost' },
        { path: 'live/register', redirect: '/ims/live/sessions' },
        { path: 'system/user', component: () => import('../views/system/user.vue') },
        { path: 'system/role', component: () => import('../views/system/role.vue') },
        { path: 'system/menu', component: () => import('../views/system/menu.vue') },
        { path: 'system/dict', component: () => import('../views/system/dict.vue') },
        { path: 'system/param', component: () => import('../views/system/param.vue') },
        { path: 'system/log', component: () => import('../views/system/log.vue') },
        { path: 'system/notify', component: () => import('../views/system/notify.vue') },
        { path: 'auth/org', component: () => import('../views/auth/org.vue') },
        { path: 'auth/position', component: () => import('../views/auth/position.vue') },
        { path: 'corp/resource/:kind', component: () => import('../views/corp/resource.vue') },
        { path: 'corp/account/:platform', component: () => import('../views/corp/account.vue') },
        { path: 'account/return', component: () => import('../views/corp/account-return.vue') },
        { path: 'corp/device/:kind', component: () => import('../views/corp/device.vue') },
        { path: 'corp/account', redirect: '/ims/corp/account/douyin' },
        { path: 'asset', redirect: '/ims/corp/device/office' },
        { path: 'cert', redirect: '/ims/corp/resource/certificate' },
        { path: 'acct', redirect: '/ims/corp/account/douyin' },
        { path: 'wip/:modId', component: () => import('../views/wip/index.vue') },
      ],
    },
    { path: '/', redirect: '/ims/workbench' },
  ],
})

router.beforeEach((to) => {
  const user = useUserStore()
  if (to.path !== '/login' && !user.accessToken) {
    return '/login'
  }
  return true
})

export default router
