-- ALERT-003 升级链路配置（#130 · BR-113）
CREATE TABLE IF NOT EXISTS ims_alert_escalate_config (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  level1_minutes INT NOT NULL DEFAULT 30,
  level2_minutes INT NOT NULL DEFAULT 60,
  severe_start_level INT NOT NULL DEFAULT 2,
  level2_extra_ids VARCHAR(512) NOT NULL DEFAULT '',
  level3_role_codes VARCHAR(128) NOT NULL DEFAULT 'R4,R1',
  deleted INT NOT NULL DEFAULT 0,
  tenant_id BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_alert_escalate_tenant (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
